<?php

$env = parse_ini_file('.env');

$MYSQL_HOST = $env['MYSQL_HOST'] or $_ENV['MYSQL_HOST'];
$MYSQL_PORT = $env['MYSQL_PORT'] or $_ENV['MYSQL_PORT'];
$MYSQL_USER = $env['MYSQL_USER'] or $_ENV['MYSQL_USER'];
$MYSQL_PASS = $env['MYSQL_PASS'] or $_ENV['MYSQL_PASS'];
$MYSQL_DTBS = $env['MYSQL_DTBS'] or $_ENV['MYSQL_DTBS'];

$ADMIN_ENCR = $env['ADMIN_ENCR'] or $_ENV['ADMIN_ENCR'];
$APPLT_ENCR = $env['APPLT_ENCR'] or $_ENV['APPLT_ENCR'];
$COMPN_ENCR = $env['COMPN_ENCR'] or $_ENV['COMPN_ENCR'];

$CIPHER_ALGO = $env['CIPHER_ALGO'] or $_ENV['CIPHER_ALGO'];

$ADMIN_COOKIE_KEY = $env['ADMIN_COOKIE_KEY'] or $_ENV['ADMIN_COOKIE_KEY'];
$APPLT_COOKIE_KEY = $env['APPLT_COOKIE_KEY'] or $_ENV['APPLT_COOKIE_KEY'];
$COMPN_COOKIE_KEY = $env['COMPN_COOKIE_KEY'] or $_ENV['COMPN_COOKIE_KEY'];
