<?php

$MYSQL_HOST = $_ENV['MYSQL_HOST'];
$MYSQL_PORT = $_ENV['MYSQL_PORT'];
$MYSQL_USER = $_ENV['MYSQL_USER'];
$MYSQL_PASS = $_ENV['MYSQL_PASS'];
$MYSQL_DTBS = $_ENV['MYSQL_DTBS'];

$ADMIN_ENCR = $_ENV['ADMIN_ENCR'];
$APPLT_ENCR = $_ENV['APPLT_ENCR'];
$COMPN_ENCR = $_ENV['COMPN_ENCR'];

$CIPHER_ALGO = $_ENV['CIPHER_ALGO'];

$ADMIN_COOKIE_KEY = $_ENV['ADMIN_COOKIE_KEY'];
$APPLT_COOKIE_KEY = $_ENV['APPLT_COOKIE_KEY'];
$COMPN_COOKIE_KEY = $_ENV['COMPN_COOKIE_KEY'];
